// <auto-generated />
using System;
using AACalc.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AACalc.Infrastructure.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20251106143612_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AACalc.Domain.Entities.AttributeKeyValueModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Key")
                        .HasColumnType("smallint");

                    b.Property<Guid>("QualityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QualityId");

                    b.HasIndex("QualityId", "Key")
                        .IsUnique();

                    b.ToTable("attributes_key_value", (string)null);
                });

            modelBuilder.Entity("AACalc.Domain.Entities.ItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte>("ItemGroup")
                        .HasColumnType("smallint");

                    b.Property<short>("ItemType")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItemType", "ItemGroup")
                        .IsUnique();

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("AACalc.Domain.Entities.QualityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<short>("QualityType")
                        .HasColumnType("smallint");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("qualities", (string)null);
                });

            modelBuilder.Entity("AACalc.Domain.Entities.SynthesisPoolModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Key")
                        .HasColumnType("smallint");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("QualityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QualityId");

                    b.HasIndex("QualityId", "Key")
                        .IsUnique();

                    b.ToTable("synthesis_pools", (string)null);
                });

            modelBuilder.Entity("AACalc.Domain.Entities.AttributeKeyValueModel", b =>
                {
                    b.HasOne("AACalc.Domain.Entities.QualityModel", "Quality")
                        .WithMany("AttributesKeyValue")
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("AACalc.Domain.Entities.QualityModel", b =>
                {
                    b.HasOne("AACalc.Domain.Entities.ItemModel", "Item")
                        .WithMany("Qualities")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AACalc.Domain.Entities.SynthesisPoolModel", b =>
                {
                    b.HasOne("AACalc.Domain.Entities.QualityModel", "Quality")
                        .WithMany("SynthesisPools")
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("AACalc.Domain.Entities.ItemModel", b =>
                {
                    b.Navigation("Qualities");
                });

            modelBuilder.Entity("AACalc.Domain.Entities.QualityModel", b =>
                {
                    b.Navigation("AttributesKeyValue");

                    b.Navigation("SynthesisPools");
                });
#pragma warning restore 612, 618
        }
    }
}
